### ISSUE TITLE
Start REPL 

### ISSUE THREAD

**Issue by edipofederle** [jgdavey/hammock#1]
Hi,

First of all, congratulations for the work. I am try start REPL and:

 `hammock --r
/Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/hammock-ruby-0.0.1.alpha/lib/clojure/core.clj:121 in seq: Error compiling: Unable to resolve symbol Hammock.LazySequence in this context (Hammock::CompileError)
    from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/hammock-ruby-0.0.1.alpha/lib/clojure/core.clj:121 in seq
    from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/hammock-ruby-0.0.1.alpha/lib/clojure/core.clj:121 in seq
    from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/hammock-ruby-0.0.1.alpha/lib/clojure/core.clj:121 in seq
    from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/hammock-ruby-0.0.1.alpha/lib/clojure/core.clj:121 in seq
    from /Users/elf/.rvm/gems/ruby-1.9.3-p547/gems/hammock-ruby-0.0.1.alpha/lib/clojure/core.clj:121 in seq
    from (root)`

This is a issue, or some problem on my side? I am walk through the code but don't found anything that can cause this problem.

**Comment by jgdavey** [comment]
I've only tested Hammock against Ruby 2.1 so far, but I'll take a look. Thanks for bringing this to my attention!

**Comment by jgdavey** [comment]
This is fixed as of 2dc0760108539743c5f7ec592dbf7b14dbcea286. Thanks!

**Comment by edipofederle** [comment]
Nice @jgdavey. :+1:
